---
title: "Avocado Price Prediction"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
avocado_df <- read_csv("/Users/ameybasangoudar/R Projects/PROJECT/avocado.csv", na = ".")
avocado_df
```


```{r}
summary(avocado_df)
```


Tidying the data
```{r}
avocado <- avocado_df %>% pivot_longer(cols = c(`4046`, `4225`, `4770`), names_to = "PLU type", values_to = "Volume of each PLU Sold")
```
```{r}
avocado <- avocado %>% pivot_longer(cols = c(`Small Bags`, `Large Bags`, `XLarge Bags`), names_to = "Bag type", values_to = "Volume of each bag sold")
```
```{r}
avocado
```
```{r}

```

```{r}
summary(avocado_df[-1])
```


```{r}
avocado
```

```{r}
avocado %>% 
  ggplot(aes(x = region, y = AveragePrice)) + 
  geom_boxplot(aes(fill = `type`)) + 
  theme(axis.text.x = element_text(angle = 90))
```



```{r}
avocado %>% 
  ggplot(aes(x = AveragePrice)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  facet_wrap(~type) +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()
```


```{r}
library(grid)
p1 <- avocado_df %>% 
  ggplot(aes(x = AveragePrice)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p2 <- avocado_df %>% 
  ggplot(aes(x = `Total Volume`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p3 <- avocado_df %>% 
  ggplot(aes(x = `4046`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p4 <- avocado_df %>% 
  ggplot(aes(x = `4225`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p5 <- avocado_df %>% 
  ggplot(aes(x = `4770`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p6 <- avocado_df %>% 
  ggplot(aes(x = `Total Bags`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p7 <- avocado_df %>% 
  ggplot(aes(x = `Small Bags`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p8 <- avocado_df %>% 
  ggplot(aes(x = `Large Bags`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()

p9 <- avocado_df %>% 
  ggplot(aes(x = `XLarge Bags`)) + 
  geom_histogram(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()


```
```{r}
vplayout <- function(x, y) viewport(layout.pos.row = x, layout.pos.col = y)

grid.newpage()
pushViewport(viewport(layout = grid.layout(3, 5))) # 3 rows, 5 columns
print(p1, vp = vplayout(1:2, 1:3))  # the big plot covers rows 1:2 and cols 1:3
print(p2, vp = vplayout(1, 4))
print(p3, vp = vplayout(1, 5))
print(p4, vp = vplayout(2, 4))
print(p5, vp = vplayout(2, 5))
print(p6, vp = vplayout(3, 1))
print(p7, vp = vplayout(3, 2))
print(p8, vp = vplayout(3, 3))
print(p9, vp = vplayout(3, 4:5))
```

```{r}
avocado_df %>% 
  ggplot(aes(x = `Total Volume`)) + 
  geom_point(aes(y = ..density..), color = 'black', fill = 'white') +
  geom_density(alpha=.2, fill="#FF6666") + theme_dark()
```

```{r}
p1 <- avocado_df %>% 
  ggplot(aes(x = AveragePrice)) + 
  geom_boxplot() + theme_dark()

p2 <- avocado_df %>% 
  ggplot(aes(x = `Total Volume`)) + 
  geom_boxplot() +
  theme_dark()

p3 <- avocado_df %>% 
  ggplot(aes(x = `4046`)) + 
  geom_boxplot() +
  theme_dark()

p4 <- avocado_df %>% 
  ggplot(aes(x = `4225`)) + 
  geom_boxplot() +
  theme_dark()

p5 <- avocado_df %>% 
  ggplot(aes(x = `4770`)) + 
  geom_boxplot() +
  theme_dark()

p6 <- avocado_df %>% 
  ggplot(aes(x = `Total Bags`)) + 
  geom_boxplot() +
  theme_dark()

p7 <- avocado_df %>% 
  ggplot(aes(x = `Small Bags`)) + 
  geom_boxplot() +
  theme_dark()

p8 <- avocado_df %>% 
  ggplot(aes(x = `Large Bags`)) + 
  geom_boxplot() +
  theme_dark()

p9 <- avocado_df %>% 
  ggplot(aes(x = `XLarge Bags`)) + 
  geom_boxplot() +
  theme_dark()


vplayout <- function(x, y) viewport(layout.pos.row = x, layout.pos.col = y)

grid.newpage()
pushViewport(viewport(layout = grid.layout(3, 5))) # 3 rows, 5 columns
print(p1, vp = vplayout(1:2, 1:3))  # the big plot covers rows 1:2 and cols 1:3
print(p2, vp = vplayout(1, 4))
print(p3, vp = vplayout(1, 5))
print(p4, vp = vplayout(2, 4))
print(p5, vp = vplayout(2, 5))
print(p6, vp = vplayout(3, 1))
print(p7, vp = vplayout(3, 2))
print(p8, vp = vplayout(3, 3))
print(p9, vp = vplayout(3, 4:5))
```
```{r}
avocado_df
```

```{r}
numer_df <- avocado_df %>% 
  select(AveragePrice, `Total Volume`, `Total Bags`, `4046`, `4225`, `4770`, `Small Bags`, `Large Bags`, `XLarge Bags`)

remove_outliers <- function(dfx, colmn){
Q <- quantile(dfx$colmn, probs=c(.25, .75), na.rm = FALSE)
iqr <- IQR(dfx$colmn)
up <-  Q[2]+1.5*iqr # Upper Range  
low<- Q[1]-1.5*iqr # Lower Range
eliminated<- subset(dfx, dfx$colmn > (Q[1] - 1.5*iqr) & dfx$colmn < (Q[2]+1.5*iqr))
eliminated
}

remove_outliers(numer_df, AveragePrice)

avocado_df %>% 
  ggplot(aes(x = AveragePrice)) + 
  geom_boxplot() + theme_dark()

new_df %>% 
  ggplot(aes(x = AveragePrice)) + 
  geom_boxplot() + theme_dark()

```


```{r}

Q <- quantile(numer_df$AveragePrice, probs=c(.25, .75), na.rm = FALSE)
iqr <- IQR(numer_df$AveragePrice)
up <-  Q[2]+1.5*iqr # Upper Range  
low<- Q[1]-1.5*iqr # Lower Range
eliminated<- subset(numer_df, numer_df$AveragePrice > (Q[1] - 1.5*iqr) & numer_df$AveragePrice < (Q[2]+1.5*iqr))


#Function to remove outliers
get_outliers <- function(x, na.rm = TRUE, ...){
  quant = quantile(x, probs = c(0.25, 0.75), na.rm = TRUE)
  limit = 1.5 * IQR(x, na.rm = na.rm, ...)
  y <- x
  y[x < (quant[1] - limit)] <- NA
  y[x > (quant[2] + limit)] <- NA
  y
} 

filtered_df <- get_outliers(numer_df)
filtered_df
```








